# Generated by Django 5.0 on 2024-01-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final_Python_App', '0005_alter_juegos_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='genero1',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='juegos',
            name='genero2',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='juegos',
            name='genero3',
            field=models.CharField(default='', max_length=32),
        ),
    ]
