# Generated by Django 5.0 on 2024-01-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final_Python_App', '0006_juegos_genero1_juegos_genero2_juegos_genero3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
