# Generated by Django 5.0 on 2024-01-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final_Python_App', '0007_alter_juegos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='juegos',
            name='subtitle',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
