# Generated by Django 5.0 on 2024-01-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final_Python_App', '0008_juegos_description_juegos_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='image2',
            field=models.ImageField(default='', upload_to='static/img/juegos'),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='image',
            field=models.ImageField(upload_to='static/img/juegos'),
        ),
    ]
