# Generated by Django 5.0 on 2024-01-17 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final_Python_App', '0009_juegos_image2_alter_juegos_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='desarrolladora',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='juegos',
            name='duracion',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='juegos',
            name='lanzamiento',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='juegos',
            name='metacritic',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='juegos',
            name='plataforma',
            field=models.CharField(default='', max_length=32),
        ),
    ]
