# Generated by Django 5.0 on 2024-01-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final_Python_App', '0010_juegos_desarrolladora_juegos_duracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='tienda',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='juegos',
            name='trailer',
            field=models.URLField(default=''),
        ),
    ]
