# Generated by Django 5.0 on 2024-01-18 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final_Python_App', '0011_juegos_tienda_juegos_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEstandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(12)])),
                ('email', models.EmailField(max_length=64, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8, 'La contraseña debe tener al menos 8 caracteres.'), django.core.validators.RegexValidator(code='invalid_password', message='La contraseña debe contener al menos un número y una letra mayúscula.', regex='^(?=.*\\d)(?=.*[A-Z]).*$')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
