# Generated by Django 5.0 on 2024-01-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final_Python_App', '0012_usuarioestandar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioestandar',
            name='email',
            field=models.EmailField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarioestandar',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarioestandar',
            name='username',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
