# Generated by Django 5.0 on 2024-01-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final_Python_App', '0013_alter_usuarioestandar_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioestandar',
            name='password',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='usuarioestandar',
            name='username',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
