# Generated by Django 5.0 on 2024-01-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final_Python_App', '0014_borrarusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrarUsuario',
        ),
    ]
