# Generated by Django 5.0 on 2024-01-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final_Python_App', '0015_usuarioestandar_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarioestandar',
            old_name='is_admin',
            new_name='is_staff',
        ),
        migrations.AddField(
            model_name='usuarioestandar',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
