# Generated by Django 5.0 on 2024-01-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final_Python_App', '0016_alter_juegos_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='image',
            field=models.ImageField(upload_to='img/juegos'),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='image2',
            field=models.ImageField(default='', upload_to='img/juegos'),
        ),
    ]
