# Generated by Django 5.0 on 2024-01-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final_Python_App', '0017_alter_juegos_image_alter_juegos_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='image',
            field=models.ImageField(upload_to='media/img/juegos'),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='image2',
            field=models.ImageField(default='', upload_to='media/img/juegos'),
        ),
    ]
