# Generated by Django 5.0 on 2024-01-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final_Python_App', '0019_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
