# Generated by Django 5.0 on 2024-01-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final_Python_App', '0024_alter_proximamente_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proximamente',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
