# Generated by Django 5.0 on 2024-01-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Final_Python_App', '0025_proximamente_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lanzamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='media/img/juegos')),
                ('fecha', models.DateField()),
                ('url', models.URLField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Proximamente',
        ),
    ]
